# Generated by Django 5.2.8 on 2026-02-06 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_preguntavideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('duracion_total', models.IntegerField(help_text='Duración en segundos')),
                ('segundos_distraido', models.IntegerField()),
                ('porcentaje_atencion', models.IntegerField()),
                ('detalle_cronologico', models.JSONField(default=list)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.recurso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
