# Generated by Django 5.2.8 on 2026-02-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtencionSesion',
        ),
    ]
