# Generated by Django 5.2.8 on 2025-12-07 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', help_text='Emoji del curso', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estudiantes', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'estudiante'}, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_impartidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='courses.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('lectura', 'Lectura'), ('quiz', 'Quiz (Test D2R)')], max_length=20)),
                ('url_contenido', models.URLField(blank=True, help_text='Link de YouTube o PDF', null=True)),
                ('contenido_texto', models.TextField(blank=True, help_text='Para lecturas', null=True)),
                ('duracion_estimada', models.CharField(default='10 min', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='courses.modulo')),
            ],
        ),
    ]
