# Generated by Django 5.2.8 on 2025-12-08 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo', models.PositiveIntegerField(help_text='Segundo exacto donde se pausa el video (ej: 90)')),
                ('texto_pregunta', models.CharField(max_length=500)),
                ('opcion_a', models.CharField(max_length=200)),
                ('opcion_b', models.CharField(max_length=200)),
                ('opcion_c', models.CharField(blank=True, max_length=200, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=200, null=True)),
                ('respuesta_correcta', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], default='A', max_length=1)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='courses.recurso')),
            ],
            options={
                'ordering': ['segundo'],
            },
        ),
    ]
