# Generated by Django 5.2.8 on 2026-02-09 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_preguntavideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionAdaptativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('facil', 'Fácil - 5 preguntas'), ('medio', 'Medio - 10 preguntas'), ('dificil', 'Difícil - 15 preguntas')], max_length=10)),
                ('preguntas_json', models.JSONField(help_text='Preguntas generadas por la IA')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('contexto_d2r', models.JSONField(blank=True, null=True)),
                ('contexto_atencion', models.JSONField(blank=True, null=True)),
                ('generada_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_adaptativas', to='courses.recurso')),
            ],
            options={
                'verbose_name': 'Evaluación Adaptativa',
                'verbose_name_plural': 'Evaluaciones Adaptativas',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_evaluacion', models.FloatField()),
                ('nivel_atencion', models.FloatField(help_text='Promedio de atención en ese recurso')),
                ('indice_d2r', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mejora_respecto_anterior', models.FloatField(blank=True, help_text='Diferencia en porcentaje', null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='courses.recurso')),
            ],
            options={
                'verbose_name': 'Evolución del Estudiante',
                'verbose_name_plural': 'Evoluciones de Estudiantes',
                'ordering': ['estudiante', 'recurso', 'fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RecursoRecomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video_youtube', 'Video de YouTube'), ('pdf', 'Documento PDF'), ('articulo', 'Artículo web'), ('ejercicio', 'Ejercicio práctico')], max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta - Ver antes de la evaluación'), ('media', 'Media - Refuerzo recomendado'), ('baja', 'Baja - Contenido complementario')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos_ia/')),
                ('generado_por_ia', models.BooleanField(default=True)),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False, help_text='Estudiante marcó como visto')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_recomendados', to=settings.AUTH_USER_MODEL)),
                ('recurso_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_generadas', to='courses.recurso')),
            ],
            options={
                'verbose_name': 'Recurso Recomendado por IA',
                'verbose_name_plural': 'Recursos Recomendados por IA',
                'ordering': ['-prioridad', '-fecha_recomendacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas_json', models.JSONField(help_text='Respuestas del estudiante')),
                ('puntaje', models.FloatField(help_text='Porcentaje de aciertos (0-100)')),
                ('tiempo_invertido', models.IntegerField(blank=True, help_text='Tiempo en segundos', null=True)),
                ('analisis_ia', models.TextField(blank=True, help_text='Comentario generado por Gemini sobre el desempeño')),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('intento_numero', models.IntegerField(default=1, help_text='Número de intento para este recurso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='courses.evaluacionadaptativa')),
            ],
            options={
                'verbose_name': 'Resultado de Evaluación',
                'verbose_name_plural': 'Resultados de Evaluaciones',
                'ordering': ['-fecha_realizacion'],
            },
        ),
    ]
