# Generated by Django 5.2.8 on 2026-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_evaluacionadaptativa_evolucionestudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursorecomendado',
            name='razon_recomendacion',
            field=models.TextField(blank=True, help_text='Explicación de por qué se recomendó', null=True),
        ),
    ]
