# Generated by Django 5.2.8 on 2025-12-16 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_preguntavideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoD2R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tr_total', models.IntegerField(help_text='Cantidad total de elementos intentados', verbose_name='Total Revisado (TR)')),
                ('ta_total', models.IntegerField(help_text='d con 2 rayas marcadas correctamente', verbose_name='Total Aciertos (TA)')),
                ('eo_total', models.IntegerField(help_text='d con 2 rayas NO marcadas', verbose_name='Errores de Omisión (EO)')),
                ('ec_total', models.IntegerField(help_text='Marcas en distractores (p o d incorrectas)', verbose_name='Errores de Comisión (EC)')),
                ('tot', models.IntegerField(help_text='TR - (EO + EC) o fórmula específica', verbose_name='Rendimiento Total (TOT)')),
                ('con', models.FloatField(help_text='TA - EC', verbose_name='Concentración (CON)')),
                ('var', models.FloatField(default=0.0, help_text='Diferencia entre el TR mayor y menor', verbose_name='Variabilidad (VAR)')),
                ('interpretacion', models.TextField(blank=True, help_text="Texto automático: 'Rendimiento Superior', 'Promedio', etc.", null=True)),
                ('curso', models.ForeignKey(help_text='Curso donde se tomó el test', on_delete=django.db.models.deletion.CASCADE, to='courses.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(help_text='El objeto recurso específico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.recurso')),
            ],
            options={
                'verbose_name': 'Resultado Test D2-R',
                'verbose_name_plural': 'Resultados Tests D2-R',
            },
        ),
        migrations.CreateModel(
            name='DetalleFilaD2R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.PositiveIntegerField(help_text='Número de fila (1 a 14)')),
                ('tr', models.IntegerField(help_text='Elementos revisados en esta fila')),
                ('ta', models.IntegerField(help_text='Aciertos en esta fila')),
                ('eo', models.IntegerField(help_text='Omisiones en esta fila')),
                ('ec', models.IntegerField(help_text='Comisiones en esta fila')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='evaluaciones.resultadod2r')),
            ],
        ),
    ]
