# Generated by Django 5.2.8 on 2026-01-26 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_preguntavideo'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion_total', models.IntegerField(help_text='Segundos que duró la sesión')),
                ('segundos_distraido', models.IntegerField(help_text='Segundos que no miró a la pantalla')),
                ('porcentaje_atencion', models.FloatField(help_text='% calculado: (1 - distracción/total) * 100')),
                ('nivel', models.CharField(choices=[('ALTA', 'Alta (>85%)'), ('MEDIA', 'Media (60-85%)'), ('BAJA', 'Baja (<60%)')], max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.recurso')),
            ],
        ),
    ]
