# Generated by Django 5.2.8 on 2026-02-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_preguntavideo'),
        ('evaluaciones', '0002_sesionatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefilad2r',
            name='ec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallefilad2r',
            name='eo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallefilad2r',
            name='numero_fila',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallefilad2r',
            name='ta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallefilad2r',
            name='tr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='con',
            field=models.FloatField(verbose_name='Concentración (CON)'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curso'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='ec_total',
            field=models.IntegerField(verbose_name='Errores de Comisión (EC)'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='eo_total',
            field=models.IntegerField(verbose_name='Errores de Omisión (EO)'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='interpretacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.recurso'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='ta_total',
            field=models.IntegerField(verbose_name='Total Aciertos (TA)'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='tot',
            field=models.IntegerField(verbose_name='Rendimiento Total (TOT)'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='tr_total',
            field=models.IntegerField(verbose_name='Total Revisado (TR)'),
        ),
        migrations.AlterField(
            model_name='resultadod2r',
            name='var',
            field=models.FloatField(default=0.0, verbose_name='Variabilidad (VAR)'),
        ),
        migrations.AlterField(
            model_name='sesionatencion',
            name='duracion_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sesionatencion',
            name='nivel',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sesionatencion',
            name='porcentaje_atencion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sesionatencion',
            name='segundos_distraido',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DetalleAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo', models.IntegerField()),
                ('es_distraido', models.BooleanField(default=False)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='evaluaciones.sesionatencion')),
            ],
        ),
    ]
